### ISSUE TITLE
Adjustment needed for NUI change in engine

### ISSUE THREAD

**Issue by Cervator** [Terasology/Zones#1]
At least I think it changed in engine as Zones no longer works :-)

Specifically OpenUiAction.onActivate uses nuiManager.pushScreen(zoneBook); where zoneBook is of a class no longer accepted by nuiManager

I'm thinking this is _probably_ a fairly easy fix

**Comment by jdrueckert** [comment]
Closing this issue based on the discussion in the comments.
Created #4 to document what we'll keep and where it went before I'll move the repo into our archive.
